
------------------------------------------------------------------------------------------
--
-- 麻将胡牌类型定义
------------------------------------------------------------------------------------------
HU_BSIXI         = 1  -- 大四喜
HU_BSANYUAN      = 2  -- 大三元
HU_JIULIANBD     = 3  -- 九莲宝灯
HU_SIGANG        = 4  -- 四杠
HU_LIANQID       = 5  -- 连七对
HU_TIANHU        = 6  -- 天和
HU_DIHU          = 7  -- 地和
HU_RENHU         = 8  -- 人和
HU_BAIWAND       = 9  -- 百万石
HU_SSIXI         = 10 -- 小四喜
HU_SSANYUAN      = 11 -- 小三元
HU_FLUSHOFZI     = 12 -- 字一色
HU_SIANKE        = 13 -- 四暗刻
HU_FLUSHOFTWOLONG= 14 -- 一色双龙会
HU_FLUSHOFSIS    = 15 -- 一色四同顺
HU_FLUSHOFSIJG   = 16 -- 一色四节高
HU_FLUSHOFSIBG   = 17 -- 一色四步高
HU_SANG          = 18 -- 三杠
HU_HUNYIJ        = 19 -- 混幺九
HU_TIANTING      = 20 -- 天听
HU_QID           = 21 -- 七对
HU_FLUSH         = 22 -- 清一色
HU_FLUSHOFSANS   = 23 -- 一色三同顺
HU_FLUSHOFSANJG  = 24 -- 一色三节高
HU_QINGLONG      = 25 -- 清龙
HU_FLUSHOFSANBG  = 26 -- 一色三步高
HU_SANANKE       = 27 -- 三暗刻
HU_MORETHANFIVE  = 28 -- 大于5
HU_SMALLTHANFIVE = 29 -- 小于5
HU_SANFENGK      = 30 -- 三风刻
HU_MIAOSHOUHC    = 31 -- 妙手回春
HU_HAIDILAOY     = 32 -- 海底捞月
HU_GANGKAI       = 33 -- 杠上开花
HU_QIANGGANG     = 34 -- 抢杠和
HU_PENGPENG      = 35 -- 碰碰和
HU_HUNYIS        = 36 -- 混一色
HU_QUANQIUREN    = 37 -- 全求人
HU_SHUANGANG     = 38 -- 双暗杠
HU_SHUANGJIANK   = 39 -- 双箭刻
HU_DAIYIJ        = 40 -- 全带幺
HU_NOCHIPG       = 41 -- 不求人
HU_SHUANGMINGG   = 42 -- 双明杠
HU_JUEZHANG      = 43 -- 和绝张
HU_LIZHI         = 44 -- 立直
HU_JIANKE        = 45 -- 箭刻
HU_QUANFENGK     = 46 -- 圈风刻
HU_MENFENGK      = 47 -- 门风刻
HU_MENQIANQ      = 48 -- 门前清
HU_PING          = 49 -- 平和
HU_SIGUIY        = 50 -- 四归一
HU_SHUANGANK     = 51 -- 双暗刻
HU_ANGANG        = 52 -- 暗杠
HU_DUANYIJIU     = 53 -- 断幺
HU_ERWUB         = 54 -- 二五八将
HU_YIJIUT        = 55 -- 幺九头
HU_BAOTING       = 56 -- 报听
HU_YIBANG        = 57 -- 一般高
HU_LIANLIU       = 58 -- 连六
HU_LAOSHAOF      = 59 -- 老少副
HU_YIJIUK        = 60 -- 幺九刻
HU_MINGG         = 61 -- 明杠
HU_BIANZH        = 62 -- 边张
HU_KANZH         = 63 -- 坎张
HU_DANDIAOJ      = 64 -- 单钓将
HU_ZIMO          = 65 -- 自摸

-- 点数定义
HU_FANSMAP= 
{
    [HU_BSIXI]         = 88, -- 大四喜
    [HU_BSANYUAN]      = 88, -- 大三元
    [HU_JIULIANBD]     = 88, -- 九莲宝灯
    [HU_SIGANG]        = 88, -- 四杠
    [HU_LIANQID]       = 88, -- 连七对
    [HU_TIANHU]        = 88, -- 天和
    [HU_DIHU]          = 88, -- 地和
    [HU_RENHU]         = 88, -- 人和
    [HU_BAIWAND]       = 88, -- 百万石
    [HU_SSIXI]         = 64, -- 小四喜
    [HU_SSANYUAN]      = 64, -- 小三元
    [HU_FLUSHOFZI]     = 64, -- 字一色
    [HU_SIANKE]        = 64, -- 四暗刻
    [HU_FLUSHOFTWOLONG]= 64, -- 一色双龙会
    [HU_FLUSHOFSIS]    = 48, -- 一色四同顺
    [HU_FLUSHOFSIJG]   = 48, -- 一色四节高
    [HU_FLUSHOFSIBG]   = 32, -- 一色四步高
    [HU_SANG]          = 32, -- 三杠
    [HU_HUNYIJ]        = 32, -- 混幺九
    [HU_TIANTING]      = 32, -- 天听
    [HU_QID]           = 24, -- 七对
    [HU_FLUSH]         = 24, -- 清一色
    [HU_FLUSHOFSANS]   = 24, -- 一色三同顺
    [HU_FLUSHOFSANJG]  = 24, -- 一色三节高
    [HU_QINGLONG]      = 16, -- 清龙
    [HU_FLUSHOFSANBG]  = 16, -- 一色三步高
    [HU_SANANKE]       = 16, -- 三暗刻
    [HU_MORETHANFIVE]  = 12, -- 大于5
    [HU_SMALLTHANFIVE] = 12, -- 小于5
    [HU_SANFENGK]      = 12, -- 三风刻
    [HU_MIAOSHOUHC]    = 8, -- 妙手回春
    [HU_HAIDILAOY]     = 8, -- 海底捞月
    [HU_GANGKAI]       = 8, -- 杠上开花
    [HU_QIANGGANG]     = 8, -- 抢杠和
    [HU_PENGPENG]      = 6, -- 碰碰和
    [HU_HUNYIS]        = 6, -- 混一色
    [HU_QUANQIUREN]    = 6, -- 全求人
    [HU_SHUANGANG]     = 6, -- 双暗杠
    [HU_SHUANGJIANK]   = 6, -- 双箭刻
    [HU_DAIYIJ]        = 4, -- 全带幺
    [HU_NOCHIPG]       = 4, -- 不求人
    [HU_SHUANGMINGG]   = 4, -- 双明杠
    [HU_JUEZHANG]      = 4, -- 和绝张
    [HU_LIZHI]         = 4, -- 立直
    [HU_JIANKE]        = 2, -- 箭刻
    [HU_QUANFENGK]     = 2, -- 圈风刻
    [HU_MENFENGK]      = 2, -- 门风刻
    [HU_MENQIANQ]      = 2, -- 门前清
    [HU_PING]          = 2, -- 平和
    [HU_SIGUIY]        = 2, -- 四归一
    [HU_SHUANGANK]     = 2, -- 双暗刻
    [HU_ANGANG]        = 2, -- 暗杠
    [HU_DUANYIJIU]     = 2, -- 断幺
    [HU_ERWUB]         = 1, -- 二五八将
    [HU_YIJIUT]        = 1, -- 幺九头
    [HU_BAOTING]       = 1, -- 报听
    [HU_YIBANG]        = 1, -- 一般高
    [HU_LIANLIU]       = 1, -- 连六
    [HU_LAOSHAOF]      = 1, -- 老少副
    [HU_YIJIUK]        = 1, -- 幺九刻
    [HU_MINGG]         = 1, -- 明杠
    [HU_BIANZH]        = 1, -- 边张
    [HU_KANZH]         = 1, -- 坎张
    [HU_DANDIAOJ]      = 1, -- 单钓将
    [HU_ZIMO]          = 1, -- 自摸
}

-- 有某种牌型时，不计番的牌型列表
HU_TYPEFILTERS = 
{
    [HU_BSIXI]          = { HU_MENFENGK, HU_QUANFENGK, HU_SSIXI, HU_SANFENGK, HU_PENGPENG, HU_YIJIUK },
    [HU_BSANYUAN]       = { HU_SSANYUAN, HU_JIANKE, HU_SHUANGJIANK, HU_YIJIUK },
    [HU_JIULIANBD]      = { HU_FLUSH, HU_NOCHIPG, HU_MENQIANQ, HU_YIJIUK },
    [HU_SIGANG]         = { HU_SHUANGANG, HU_SHUANGMINGG, HU_SANG, HU_ANGANG, HU_MINGG, HU_DANDIAOJ },
    [HU_LIANQID]        = { HU_FLUSH, HU_NOCHIPG, HU_DANDIAOJ, HU_MENQIANQ, HU_QID, HU_LIANLIU, HU_YIBANG },
    [HU_TIANHU]         = { HU_DANDIAOJ, HU_BIANZH, HU_KANZH },
    [HU_BAIWAND]        = { HU_FLUSH },
    [HU_SSIXI]          = { HU_SANFENGK, HU_YIJIUK },
    [HU_SSANYUAN]       = { HU_JIANKE, HU_SHUANGJIANK, HU_YIJIUK },
    [HU_FLUSHOFZI]      = { HU_PENGPENG, HU_HUNYIJ, HU_DAIYIJ, HU_YIJIUK },
    [HU_SIANKE]         = { HU_MENQIANQ, HU_PENGPENG, HU_SANANKE, HU_SHUANGANK, HU_NOCHIPG, HU_FLUSHOFSANS, HU_YIBANG },
    [HU_FLUSHOFTWOLONG] = { HU_PING, HU_QID, HU_FLUSH, HU_YIBANG, HU_LAOSHAOF  },
    [HU_FLUSHOFSIS]     = { HU_FLUSHOFSANS, HU_FLUSHOFSANJG, HU_YIBANG, HU_SIGUIY, HU_QID, HU_SANANKE, HU_SHUANGANK, HU_YIJIUK },
    [HU_FLUSHOFSIJG]    = { HU_FLUSHOFSANS, HU_FLUSHOFSANJG, HU_PENGPENG, HU_YIBANG, HU_PING },
    [HU_FLUSHOFSIBG]    = { HU_FLUSHOFSANBG, HU_LAOSHAOF, HU_LIANLIU },
    [HU_SANG]           = { HU_SHUANGMINGG, HU_SHUANGANG, HU_MINGG, HU_ANGANG },
    [HU_HUNYIJ]         = { HU_PENGPENG, HU_YIJIUK, HU_DAIYIJ },
    [HU_QID]            = { HU_MENQIANQ, HU_NOCHIPG, HU_DANDIAOJ },
    [HU_FLUSHOFSANS]    = { HU_FLUSHOFSANJG, HU_YIBANG },
    [HU_FLUSHOFSANJG]   = { HU_FLUSHOFSANS, HU_YIBANG, HU_PING },
    [HU_QINGLONG]       = { HU_LIANLIU, HU_LAOSHAOF },
    [HU_SANANKE]        = { HU_SHUANGANK },
    [HU_TIANTING]       = { HU_LIZHI, HU_BAOTING },
    [HU_SANFENGK]       = { HU_YIJIUK },
    [HU_MIAOSHOUHC]     = { HU_ZIMO  },
    [HU_GANGKAI ]       = { HU_ZIMO },
    [HU_QIANGGANG]      = { HU_JUEZHANG },
    [HU_QUANQIUREN]     = { HU_DANDIAOJ },
    [HU_SHUANGANG]      = { HU_SHUANGANK, HU_ANGANG },
    [HU_SHUANGJIANK]    = { HU_JIANKE },
    [HU_NOCHIPG]        = { HU_MENQIANQ, HU_ZIMO },
    [HU_SHUANGMINGG]    = { HU_MINGG },
    [HU_JUEZHANG]       = { HU_QIANGGANG },
    [HU_LIZHI]          = { HU_BAOTING, HU_MENQIANQ },
    [HU_BIANZH]         = { HU_DANDIAOJ, HU_KANZH },
    [HU_KANZH]          = { HU_DANDIAOJ },
    [HU_JIANKE]         = { HU_YIJIUK },
    [HU_QUANFENGK]      = { HU_YIJIUK },
    [HU_MENFENGK]       = { HU_YIJIUK },
}

-- 风箭麻将牌的定义
MJ_Card_East  = 41	-- 东
MJ_Card_South = 42  -- 南
MJ_Card_West  = 43  -- 西
MJ_Card_North = 44  -- 北
MJ_Card_Zhong = 45  -- 中
MJ_Card_Fa    = 46  -- 發
MJ_Card_Bai   = 47  -- 白

-- 操作定义
HU            = 0x00000001        -- 胡
PENG          = 0x00000002        -- 碰
ZHI_GANG      = 0x00000004        -- 直杠
PENG_GANG     = 0x00000008        -- 面下 先碰后杠
AN_GANG       = 0x00000010        -- 暗杠
LCHI          = 0x00000020        -- 吃前面张
MCHI          = 0x00000040        -- 吃中间张
RCHI          = 0x00000080        -- 吃后面张
BUHA          = 0x00000100        -- 补花
PLAYCARD      = 0x00000200        -- 出牌
CANCEL        = 0x00000400        -- 取消
TING          = 0x00000800        -- 听牌
GETCARD       = 0x00001000        -- 获得牌（发新牌
CHI_TING      = 0x00002000        -- 吃听
PENG_TING     = 0x00004000        -- 碰听
RESERVE       = 0x00010000        -- 保留操作，用于游戏中自定义操作